substitutions:
  device_name: "BlitzWolf BW-SHP6 ED007D"
  device_name_lower: "blitzwolf_bw_shp6_ed007d"
  device_hostname: "blitzwolf-bw-shp6-ed007d"
  current_res: "0.00290"
  voltage_div: "940"

esphome:
  name: ${device_name_lower}
  platform: ESP8266
  board: esp8285

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: ${device_hostname}
  domain: !secret local_domain
  ap:
    ssid: ${device_name}
    password: !secret esphome_password

captive_portal:

logger:

api:
  password: !secret esphome_password

ota:
  password: !secret esphome_password

web_server:
  port: 80

binary_sensor:
  - platform: gpio
    id: button
    internal: true
    pin:
      number: GPIO13
    on_press:
      - switch.toggle: relay

output:
  - platform: gpio
    pin: GPIO00
    inverted: true
    id: led

switch:
  - platform: gpio
    pin: GPIO15
    id: relay
    icon: mdi:power-plug
    name: "${device_name} Relay"
    on_turn_on:
      - output.turn_on: led
    on_turn_off:
      - output.turn_off: led

  - platform: restart
    name: "${device_name} Restart"

status_led:
  pin:
    number: GPIO02
    inverted: true

sensor:
  - platform: uptime
    name: "${device_name} Uptime"
    unit_of_measurement: days
    update_interval: 300s
    filters:
      - multiply: 0.000011574

  - platform: wifi_signal
    name: "${device_name} WiFi Signal"
    update_interval: 300s

  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: true
    cf_pin: GPIO05
    cf1_pin: GPIO14
    current_resistor: ${current_res}
    voltage_divider: ${voltage_div}
    current:
      name: "${device_name} Current"
      unit_of_measurement: "A"
      accuracy_decimals: 3
      icon: mdi:flash-outline
    voltage:
      name: "${device_name} Voltage"
      unit_of_measurement: "V"
      icon: mdi:flash-outline
    power:
      name: "${device_name} Power"
      unit_of_measurement: "W"
      icon: mdi:flash-outline
    change_mode_every: 4
